# Generated by Django 6.0.7 on 2026-07-09 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv_id', models.CharField(max_length=12, unique=True)),
                ('beacon_type', models.CharField(choices=[('gate', 'Gate'), ('store', 'Store'), ('common', 'Common')], default='common', max_length=8)),
                ('pos_x', models.IntegerField(default=0)),
                ('pos_y', models.IntegerField(default=0)),
                ('tx_power', models.IntegerField(default=-59)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=80)),
                ('plan_image', models.FileField(blank=True, upload_to='floors/')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, upload_to='campaigns/')),
                ('coupon', models.CharField(blank=True, max_length=40)),
                ('discount', models.CharField(blank=True, max_length=40)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_beacons', models.ManyToManyField(blank=True, related_name='campaigns', to='core.beacon')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_hash', models.CharField(max_length=64)),
                ('triggered_at', models.DateTimeField()),
                ('delivered', models.BooleanField(default=True)),
                ('opened', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='core.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='beacon',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beacons', to='core.floor'),
        ),
        migrations.AddField(
            model_name='floor',
            name='mall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='core.mall'),
        ),
        migrations.CreateModel(
            name='CacheVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mall', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cache_version', to='core.mall')),
            ],
        ),
        migrations.AddField(
            model_name='beacon',
            name='mall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beacons', to='core.mall'),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=60)),
                ('pos_x', models.IntegerField(default=0)),
                ('pos_y', models.IntegerField(default=0)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='core.floor')),
                ('keeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to=settings.AUTH_USER_MODEL)),
                ('mall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='core.mall')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='core.store'),
        ),
        migrations.AddField(
            model_name='beacon',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beacons', to='core.store'),
        ),
        migrations.CreateModel(
            name='LocationPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('device_hash', models.CharField(max_length=64)),
                ('store_id', models.IntegerField(null=True)),
                ('mall_id', models.IntegerField()),
                ('rssi', models.IntegerField()),
                ('est_distance', models.FloatField()),
                ('beacon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pings', to='core.beacon')),
            ],
            options={
                'indexes': [models.Index(fields=['mall_id', 'time'], name='core_locati_mall_id_67ed40_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_hash', 'beacon', 'time'), name='uniq_ping')],
            },
        ),
    ]
