# Generated by Django 6.0.7 on 2026-07-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='badge',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.FileField(blank=True, upload_to='stores/'),
        ),
        migrations.AddField(
            model_name='store',
            name='tagline',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
