# Generated by Django 6.0.7 on 2026-07-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_store_badge_store_image_store_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='pixels_per_meter',
            field=models.FloatField(default=4.0),
        ),
    ]
