# Generated by Django 6.0.7 on 2026-07-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_floor_pixels_per_meter'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='shape',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
