# Generated by Django 6.0.7 on 2026-07-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_store_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='height_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='width_m',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
