# Generated by Django 6.0.7 on 2026-07-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_floor_height_m_floor_width_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='outline',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
