# Generated by Django 6.0.7 on 2026-07-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_floor_outline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='pixels_per_meter',
        ),
    ]
